spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jpa:
    hibernate:
      ddl-auto=: create